#!/usr/bin/env python
# #coding:utf8

import StringIO
import os
import xml.etree.ElementTree as ET

import yaml


def parse_config():
    yaml_config = 'jenkins-compose.yml'
    with open(yaml_config) as f:
        config = yaml.load(f)
        return config


def get_artifactory_config(name):
    config = parse_config()
    jobs = config['jobs']
    for job in jobs:
        if job['name'] == name:
            return job['artifactory']
    return None


def get_jobs_config(job_type):
    """

    :param job_type: release| feature| ci
    :return:
    """
    job_list = []
    config = parse_config()
    jobs = config['jobs']
    for job in jobs:
        if job_type == 'ci':
            job_list.append(job['name'])
        elif job.get(job_type, False):
            job_list.append(job['name'])
    return job_list


def remove_publisher(conf_file):
    tree = ET.parse(conf_file)
    root = tree.getroot()
    try:
        pub = root.find('publishers')
        for item in pub:
            if item.tag == 'org.jfrog.hudson.ArtifactoryRedeployPublisher':
                pub.remove(item)
                print("ArtifactoryRedeployPublisher section removed from %s" % conf_file)
        tree.write(conf_file)
    except:
        print("%s has no publishers." % conf_file)


def xml_string_to_element(xml_string):
    xml_file = StringIO.StringIO(xml_string)
    tree = ET.parse(xml_file)
    element = tree.getroot()
    return element


def find_parameter(tree):
    return tree.find("./properties/hudson.model.ParametersDefinitionProperty")


def find_properties(tree):
    return tree.find("./properties")


def add_parameter(tree):
    parameter_definition_xml = """
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions>
        <hudson.model.StringParameterDefinition>
          <name>gitlabSourceBranch</name>
          <description></description>
          <defaultValue></defaultValue>
        </hudson.model.StringParameterDefinition>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
"""
    parameter_definition_xml_file = StringIO.StringIO(parameter_definition_xml)
    parameter_definition_tree = ET.parse(parameter_definition_xml_file)
    parameter_definition_element = parameter_definition_tree.getroot()
    # print parameter_definition_tree

    parameterProperty = find_parameter(tree)
    properties = find_properties(tree)

    for child in properties:
        if child.tag == 'hudson.model.ParametersDefinitionPropert':
            properties.remove(child)
    properties.append(parameter_definition_element)


def print_element(element):
    print "print element ", element
    for child in element:
        print child.tag, child.attrib, child.text


def find_refspec(tree):
    return tree.find("./scm/userRemoteConfigs/hudson.plugins.git.UserRemoteConfig/refspec")


def find_urc(tree):
    return tree.find("./scm/userRemoteConfigs/hudson.plugins.git.UserRemoteConfig")


def set_refspec(tree):
    urc = find_urc(tree)
    refspec = find_refspec(tree)
    if refspec is None:
        urc.append(ET.Element("refspec"))

    refspec = find_refspec(tree)
    refspec.text = "+refs/heads/*:refs/remotes/origin/* +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*"


def find_branches(tree):
    return tree.find("./scm/branches/hudson.plugins.git.BranchSpec")


def set_branches(tree):
    branch = find_branches(tree)
    for child in branch:
        if child.tag == "name":
            child.text = 'origin/${gitlabSourceBranch}'


def find_gitlab_trigger(tree):
    return tree.find("./triggers/com.dabsquared.gitlabjenkins.GitLabPushTrigger")


def set_gitlab_triggers(tree):
    gitlab_trigger = find_gitlab_trigger(tree)
    for child in gitlab_trigger:
        if child.tag == 'branchFilterType':
            child.text = r"RegexBasedFilter"
        if child.tag == 'targetBranchRegex':
            child.text = r"^\d+.\d+.[xX]$"
        if child.tag == 'includeBranchesSpec':
            child.text = r""


def find_artifactory_publisher(tree):
    return tree.find("./publishers/org.jfrog.hudson.ArtifactoryRedeployPublisher")


def find_publisher(tree):
    return tree.find("./publishers")


def remove_artifactory_publisher(tree):
    publisher = find_publisher(tree)
    for child in publisher:
        if child.tag == 'org.jfrog.hudson.ArtifactoryRedeployPublisher':
            publisher.remove(child)


def set_artifactory_publisher(tree, artifactory):
    artifactory_xml_tmpl = """<org.jfrog.hudson.ArtifactoryRedeployPublisher plugin="artifactory@2.5.0">
      <evenIfUnstable>false</evenIfUnstable>
      <details>
        <artifactoryName>datayes-artifactory</artifactoryName>
        <artifactoryUrl>http://artifactory.datayes.com/artifactory</artifactoryUrl>
        <deployReleaseRepository>
          <keyFromText></keyFromText>
          <keyFromSelect>{artifactory_name}</keyFromSelect>
          <dynamicMode>false</dynamicMode>
        </deployReleaseRepository>
        <deploySnapshotRepository>
          <keyFromText></keyFromText>
          <keyFromSelect>{artifactory_name}</keyFromSelect>
          <dynamicMode>false</dynamicMode>
        </deploySnapshotRepository>
        <stagingPlugin>
          <pluginName>None</pluginName>
        </stagingPlugin>
        <userPluginKey>None</userPluginKey>
      </details>
      <deployArtifacts>true</deployArtifacts>
      <artifactDeploymentPatterns>
        <includePatterns></includePatterns>
        <excludePatterns></excludePatterns>
      </artifactDeploymentPatterns>
      <deployerCredentialsConfig>
        <credentials>
          <username></username>
          <password></password>
        </credentials>
        <credentialsId></credentialsId>
        <overridingCredentials>false</overridingCredentials>
      </deployerCredentialsConfig>
      <includeEnvVars>false</includeEnvVars>
      <envVarsPatterns>
        <includePatterns></includePatterns>
        <excludePatterns>*password*,*secret*,*key*</excludePatterns>
      </envVarsPatterns>
      <runChecks>false</runChecks>
      <violationRecipients></violationRecipients>
      <includePublishArtifacts>false</includePublishArtifacts>
      <passIdentifiedDownstream>false</passIdentifiedDownstream>
      <scopes></scopes>
      <licenseAutoDiscovery>true</licenseAutoDiscovery>
      <disableLicenseAutoDiscovery>false</disableLicenseAutoDiscovery>
      <discardOldBuilds>false</discardOldBuilds>
      <discardBuildArtifacts>true</discardBuildArtifacts>
      <matrixParams></matrixParams>
      <enableIssueTrackerIntegration>false</enableIssueTrackerIntegration>
      <allowPromotionOfNonStagedBuilds>false</allowPromotionOfNonStagedBuilds>
      <allowBintrayPushOfNonStageBuilds>false</allowBintrayPushOfNonStageBuilds>
      <filterExcludedArtifactsFromBuild>true</filterExcludedArtifactsFromBuild>
      <recordAllDependencies>false</recordAllDependencies>
      <defaultPromotionTargetRepository></defaultPromotionTargetRepository>
      <deployBuildInfo>true</deployBuildInfo>
      <aggregationBuildStatus>Released</aggregationBuildStatus>
      <aggregateBuildIssues>false</aggregateBuildIssues>
      <blackDuckRunChecks>false</blackDuckRunChecks>
      <blackDuckAppName></blackDuckAppName>
      <blackDuckAppVersion></blackDuckAppVersion>
      <blackDuckReportRecipients></blackDuckReportRecipients>
      <blackDuckScopes></blackDuckScopes>
      <blackDuckIncludePublishedArtifacts>false</blackDuckIncludePublishedArtifacts>
      <autoCreateMissingComponentRequests>true</autoCreateMissingComponentRequests>
      <autoDiscardStaleComponentRequests>true</autoDiscardStaleComponentRequests>
    </org.jfrog.hudson.ArtifactoryRedeployPublisher>
"""
    artifactory_xml = artifactory_xml_tmpl.format(artifactory_name=artifactory)
    artifactory_publisher = find_artifactory_publisher(tree)
    remove_artifactory_publisher(tree)
    artifactory_element = xml_string_to_element(artifactory_xml)

    publisher = find_publisher(tree)
    publisher.append(artifactory_element)


def add_script_in_pre_builder(tree):
    """for feature"""
    script_element = """
    <hudson.tasks.Shell>
      <command>
#!/usr/bin/env bash
pom=&quot;/home/jenkins/workspace/${JOB_NAME}/pom.xml&quot;
version=`expr ${gitlabSourceBranch} : '\([A-Za-z]*-[0-9]*\)'`
sed -i &quot;s/{BUILD_NUMBER}/{BUILD_NUMBER}-${version}/g&quot; $pom</command>
    </hudson.tasks.Shell>
    """

    root_element = tree.find("./prebuilders")
    shell_element = xml_string_to_element(script_element)
    root_element.append(shell_element)


def add_remote_token(tree):
    token_str = "<authToken>mommp2017</authToken>"
    root_element = tree.getroot()
    token_ele = xml_string_to_element(token_str)
    root_element.append(token_ele)


def update_ci_xml(conf_file):
    """ update xml """
    tree = ET.parse(conf_file)
    remove_artifactory_publisher(tree)

    tree.write(conf_file)


def update_release_xml(name, conf_file, target_file):
    """ update xml """
    tree = ET.parse(conf_file)
    set_refspec(tree)
    set_branches(tree)
    set_gitlab_triggers(tree)
    add_parameter(tree)

    artifactory = get_artifactory_config(name)
    set_artifactory_publisher(tree, artifactory)

    tree.write(target_file)


def update_feature_xml(name, conf_file, target_file):
    """ update xml """
    tree = ET.parse(conf_file)
    set_refspec(tree)
    set_branches(tree)
    add_parameter(tree)
    remove_artifactory_publisher(tree)
    add_remote_token(tree)
    add_script_in_pre_builder(tree)
    tree.write(target_file)


def get_all_jobs(path):
    jobs = os.listdir(path)
    ci_jobs = []
    for job in jobs:
        if not job.endswith('-release') \
                and not job.endswith('-feature') \
                and not job.startswith('pms'):
            ci_jobs.append(job)

    return ci_jobs


def add_job(job, path, job_type):
    """

    :param job:
    :param path:
    :param job_type: release|feature
    :return:
    """
    suffix = '-%s' % job_type
    print "process %s job " % job_type, job

    job_path = path + "/" + job
    job_config = job_path + '/config.xml'
    release_job_name = job + suffix
    release_job_path = path + "/" + release_job_name
    if not os.path.exists(release_job_path):
        os.mkdir(release_job_path)

    release_job_config = release_job_path + '/config.xml'
    if job_type == 'release':
        update_release_xml(job, job_config, release_job_config)
    elif job_type == 'feature':
        update_feature_xml(job, job_config, release_job_config)


def main():
    path = '/datayes/automation-infrastructure/ci/jenkins/data-prod/jobs'
    # path = '/root/workspace/automation-infrastructure/ci/jenkins/data-prod/jobs'

    all_jobs = get_all_jobs(path)

    # clear ci jobs
    job_type = 'ci'
    config_jobs = get_jobs_config(job_type)
    for job in (set(all_jobs) & set(config_jobs)):
        job_config = os.path.join(path, job, "config.xml")
        update_ci_xml(job_config)

    job_type = 'release'
    config_jobs = get_jobs_config(job_type)
    for job in (set(all_jobs) & set(config_jobs)):
        add_job(job, path, job_type)

    job_type = 'feature'
    config_jobs = get_jobs_config(job_type)
    for job in (set(all_jobs) & set(config_jobs)):
        add_job(job, path, job_type)


if __name__ == "__main__":
    main()
